repos:
  - repo: local
    hooks:
      - id: cargo-clippy
        name: Run cargo clippy
        entry: cargo clippy --fix --allow-staged --workspace --all-targets --all-features --locked -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
